/** @format */

const cities = [
  "New York",
  "London",
  "Paris",
  "Tokyo", 
  "Hong Kong",
  "Rome",
  "Dubai",
  "Barcelona",
  "Singapore",
  "Bangkok",
  "Istanbul", 
  "Vienna",
  "Sydney",
  "Moscow",
  "Los Angeles",
  "Seoul",
  "San Francisco",
  "St Petersburg",
  "Madrid", 
  "Nice",
  "Toronto",
  "Munich",
  "Venice",
  "Melbourne",
  "Florence", 
  "Chicago",
  "Cancun", 
  "Cape Town",
  "Las Vegas",
  "Rio De Janeiro",
  "Amsterdam",
  "Manila",
  "Athens",
  "Abu Dhabi",
  "Kyoto",
  "Nairobi",
  "Dublin",
  "Phuket",
  "Saint Tropez",
  "Cozenza",
  "Marrakesh",
  "Shanghai",
  "San Diego",
  "Berlin",
  "Miami",
  "Bali",
  "Lisbon",
  "Myrtle Beach",
  "Jeju Island",
  "Zurich",
  "Ciudad De Mexico",
  "Copenhagen",
  "Scottadale",
  "Buenos Aires",
  "Budapest", 
  "Mauritius",
  "Stockholm",
  "Belgrade",
  "Prague",
  "Xiamen",
  "Hamburg",
  "Warsaw", 
  "Hvar", 
  "Seville",
  "Monaco",
  "Edinburgh",
  "Sao Paulo",
  "Johannesburg",
  "Hoi An",
  "Bruges", 
  "Paulo",
  "Boston", 
  "Medina",
  "Mumbai",
  "Delhi",
  "Hanoi", 
  "Brussels",
  "San Eun-Tae",
  "Osaka",
  "Luang Prabang",
  "Montreal",
  "Vancouver",
  "Lucerne",
  "Pula", 
  "Doha",
  "Marseille",
  "Santorini",
  "Beijing",
  "Lebong",
  "Krakow",
  "Cordoba",
  "Valencia", 
  "Saint Petersburg",
  "Chiang Mai",
  "Fukuoka",
  "Puerto Vallarta",
  "Siem Reap",
  "Cinque Terre",
  "Geneva",
  "Sharm El Sheikh",
  "Medellin",
  "Panama City",
  "Naples",
  "Sofia",
  "Girona", 
  "Kuta",
  "Seville", 
  "Playa Del Carmen",
  "Anchorage",
  "Rosario",
  "Austin",
  "Portland",
  "Kansas City",
  "Washington",
  "Milan", 
  "Vientiane",
  "Nadi",
  "Granada",
  "Split",
  "Jerusalem",
  "Honolulu",
  "Bora Bora",
  "Gdansk",
  "Santiago",
  "Denver",
  "Hanoi",
  "Tallinn", 
  "Taipei",
  "Omaha", 
  "Meteora",
  "Luanda",
  "Zagreb",  
  "Portland",
  "Colombo",
  "Antwerp",
  "Key West",
  "Cusco",
  "Savannah",
  "Palermo",
  "Incheon",
  "Banff",
  "Halong Bay",
  "Mendoza",
  "Bled",
  "Opatija",
  "Copenhagen",
  "Durban",
  "Corfu",
  "Jaipur",
  "Naha",
  "Hilo",
  "Cairns", 
  "Casablanca",
  "Kobe",
  "Agra",
  "Reykjavik",
  "Oslo",
  "Malaga",
  "La Paz",
  "Cartagena",
  "Essaouira",
  "Nashville",
  "Gdansk",
  "Seogwipo",
  "Valparaiso",
  "Galway",
  "Verona",
  "Sorrento",
  "Baku",
  "Kathmandu",
  "Tbilisi",
  "Kotor",
  "Santa Cruz",
  "Bratislava",
  "Salzburg",
  "Sofia",
  "Baltimore",
  "Salvador",
  "Luxembourg", 
  "Busan",
  "Mexico City", 
  "Belfast",
  "Goteborg",
  "Auckland",
  "Sedona",
  "Vilnius",
  "Interlaken",
  "Dakar",
  "Salento",
  "Asheville",
  "Byron Bay",
  "Queenstown",
  "Galapagos Islands",
  "Varna",  
  "Sarajevo",
  "Brooklyn",
  "Zadar", 
  "Pompeii",
  "Guayaquil",
  "Ibiza",
  "Breckenridge", 
  "Chengdu",
  "Sibenik", 
  "Bucharest",
  "Liege",
  "Washington D.C.",
  "Taipei",
  "Oxford",
  "Ko Phi Phi",
  "New Orleans",
  "Birmingham",
  "Charleston",
  "Bled Slovenia",
  "Mostar",
  "Avignon",
  "Frankfurt",
  "Sihanoukville Cambodia",
  "La Spezia",
  "Ushuaia",
  "Tasmania",
  "Riga",
  "Ljubljana",
  "Alexandria",
  "Dead Sea",
  "victoria",
  "Pisa",
  "Bern",
  "Norrkoping Sweden",
  "La Paz Boliva",
  "Hvar Island Croatia",
  "Suva Fiji",
  "Heidelberg Germany",
  "Harbin China", 
  "Hallstatt Austria",
  "Grand baie Mauritius",
  "Guilin China",
  "Bordeaux France", 
  "Svalbard Norway",
  "Colorado Springs", 
  "Ubud Bali",
  "Jacksonville",
  "Rejkavik",
  "pensacola",
  "Graz Austria",  
  "Vilnius Lithuania", 
  "Positano",
  "Great Smoky Mountain",
  "Mt Fuji",
  "Negril Jamaica",
  "Ocho Rios", 
  "El Nido",
  "Loire Valley",
  "Pensicola",
  "Bergen",
  "El Paso",
  "Victoria Falls",  
  "Iguazu Falls",
  "Cochem Germany",  
  "Siena",
  "Yangon Myanmar",
  "Calcata Italy",
  "Bay Islands Honduras",
  "Champaign",
  "Williamsburg VA",
  "Bern Switzerland",
  "Turin Italy",
  "Salt Lake City",
  "Kochi India",
  "Amman",
  "Boca Raton",
  "Chania Crete Greece",
  "Baden Baden Germany",
  "Lake Tahoe",
  "St. Thomas",
  "Woodstock",
  "Providence RI", 
  "Osijek Croatia",
  "Uppsala Sweden",
  "hanoi",
  "vail",
  "new delhi",
  "Lijang China",
  "Tarragona Spain",
  "Tromso Norway",
  "Jaipur India",
  "Ronda Spain",
  "Jeju South Korea",
  "Kerry Ireland",
  "Viterbo Italy",  
  "Oklahoma City",
  "Vinales Cuba",
  "Plovdiv",
  "Quito Ecuador",
  "Saint John NB",
  "Georgetown D.C.",
  "Novi Sad Serbia",
  "Charlottetown Pei",
  "Lauterbrunnen Switzerland",
  "Rethymno Crete",
  "La Paz Mexico",
  "Cesky Krumlov",
  "Berat Albania",
  "Guangzhou China",
  "New Delhi India",
  "la spezia", 
  "Cagliari",
  "Palma de Mallorca",
  "Larnaca",
  "Chania", 
  "Effiel Tower",
  "Parthenon",   
  "Neuschwanstein Castle",
  "Machu Picchu",
  "Sydney Opera House",
  "Mumbai",
  "St. Basil's Cathedral",  
  "Kuala Lumpur",
  "Anchorage",
  "Valletta",
  "Port Au Prince",
  "Port Au Prince",
  "Palmeira",
  "Changde",
  "Bhaktapur",
  "Havana",
  "Kobarid",
  "Skopje",
  "Victor Harbour",
  "Guadeloupe",
  "Aswan", 
  "Reykholt",
  "Chiang Saen",
  "Savusavu",
  "Heraklion",
  "Stein Am Rhein",
  "Portsmouth",
  "Kotor",
  "Thrissur",
  "Nauplia",
];
export const getCityNameByInput = async (value) => {
  try {
    const response = await fetch(
      `https://api.teleport.org/api/cities/?search=${value}`
    );
    const data = await response.json();
    return data._embedded["city:search-results"];
  } catch (error) {
    console.error(error);
    return [];
  }
};
